"""
KhetOptima Crop Database - Indian crops with economics, agronomy and market data.
Values are realistic estimates for 2024-26 Indian agriculture.
All monetary values in INR per acre unless noted.
"""
from typing import Dict, List

# Crop encyclopedia - 16 major crops across Rabi, Kharif, Zaid
CROP_DATABASE: Dict[str, dict] = {
    "wheat": {
        "name": "Wheat",
        "season": "Rabi",
        "category": "Cereal",
        "duration_days": 120,
        "yield_quintal_per_acre": 18.0,
        "price_per_quintal": 2275,  # MSP 2024-25
        "cost_per_acre": 14500,
        "water_requirement_mm": 450,
        "water_level": "Medium",
        "soil_suitability": {"loamy": 95, "clay": 85, "sandy": 60, "black": 80, "red": 70, "alluvial": 92},
        "risk_score": 0.25,
        "risk_label": "Low",
        "msp": 2275,
        "demand_trend": "Stable",
        "rotation_benefit": "Medium",
        "labour_days_per_acre": 18,
        "sustainability_score": 72,
        "glut_risk": "Low",
    },
    "rice": {
        "name": "Rice (Paddy)",
        "season": "Kharif",
        "category": "Cereal",
        "duration_days": 130,
        "yield_quintal_per_acre": 22.0,
        "price_per_quintal": 2300,
        "cost_per_acre": 18500,
        "water_requirement_mm": 1200,
        "water_level": "Very High",
        "soil_suitability": {"loamy": 88, "clay": 95, "sandy": 45, "black": 70, "red": 55, "alluvial": 96},
        "risk_score": 0.35,
        "risk_label": "Medium",
        "msp": 2300,
        "demand_trend": "High",
        "rotation_benefit": "Low",
        "labour_days_per_acre": 28,
        "sustainability_score": 48,
        "glut_risk": "Medium",
    },
    "mustard": {
        "name": "Mustard",
        "season": "Rabi",
        "category": "Oilseed",
        "duration_days": 110,
        "yield_quintal_per_acre": 8.5,
        "price_per_quintal": 5650,
        "cost_per_acre": 11500,
        "water_requirement_mm": 280,
        "water_level": "Low",
        "soil_suitability": {"loamy": 92, "clay": 75, "sandy": 82, "black": 78, "red": 85, "alluvial": 88},
        "risk_score": 0.28,
        "risk_label": "Low",
        "msp": 5650,
        "demand_trend": "High",
        "rotation_benefit": "High",
        "labour_days_per_acre": 14,
        "sustainability_score": 85,
        "glut_risk": "Low",
    },
    "chickpea": {
        "name": "Chickpea (Gram)",
        "season": "Rabi",
        "category": "Pulse",
        "duration_days": 110,
        "yield_quintal_per_acre": 9.0,
        "price_per_quintal": 5440,
        "cost_per_acre": 10800,
        "water_requirement_mm": 300,
        "water_level": "Low",
        "soil_suitability": {"loamy": 88, "clay": 70, "sandy": 90, "black": 85, "red": 92, "alluvial": 80},
        "risk_score": 0.30,
        "risk_label": "Low",
        "msp": 5440,
        "demand_trend": "High",
        "rotation_benefit": "Very High",
        "labour_days_per_acre": 15,
        "sustainability_score": 90,
        "glut_risk": "Low",
    },
    "cotton": {
        "name": "Cotton",
        "season": "Kharif",
        "category": "Cash Crop",
        "duration_days": 180,
        "yield_quintal_per_acre": 7.5,
        "price_per_quintal": 7121,
        "cost_per_acre": 22000,
        "water_requirement_mm": 700,
        "water_level": "High",
        "soil_suitability": {"loamy": 82, "clay": 60, "sandy": 55, "black": 96, "red": 65, "alluvial": 75},
        "risk_score": 0.55,
        "risk_label": "High",
        "msp": 7121,
        "demand_trend": "Medium",
        "rotation_benefit": "Low",
        "labour_days_per_acre": 35,
        "sustainability_score": 55,
        "glut_risk": "Medium",
    },
    "soybean": {
        "name": "Soybean",
        "season": "Kharif",
        "category": "Oilseed",
        "duration_days": 100,
        "yield_quintal_per_acre": 10.0,
        "price_per_quintal": 4892,
        "cost_per_acre": 13200,
        "water_requirement_mm": 500,
        "water_level": "Medium",
        "soil_suitability": {"loamy": 85, "clay": 65, "sandy": 60, "black": 92, "red": 78, "alluvial": 80},
        "risk_score": 0.32,
        "risk_label": "Medium",
        "msp": 4892,
        "demand_trend": "High",
        "rotation_benefit": "High",
        "labour_days_per_acre": 16,
        "sustainability_score": 82,
        "glut_risk": "Low",
    },
    "maize": {
        "name": "Maize",
        "season": "Kharif",
        "category": "Cereal",
        "duration_days": 95,
        "yield_quintal_per_acre": 20.0,
        "price_per_quintal": 2090,
        "cost_per_acre": 13800,
        "water_requirement_mm": 550,
        "water_level": "Medium",
        "soil_suitability": {"loamy": 90, "clay": 70, "sandy": 75, "black": 72, "red": 88, "alluvial": 85},
        "risk_score": 0.27,
        "risk_label": "Low",
        "msp": 2090,
        "demand_trend": "High",
        "rotation_benefit": "Medium",
        "labour_days_per_acre": 17,
        "sustainability_score": 74,
        "glut_risk": "Low",
    },
    "tomato": {
        "name": "Tomato",
        "season": "Zaid",
        "category": "Vegetable",
        "duration_days": 90,
        "yield_quintal_per_acre": 80.0,
        "price_per_quintal": 1400,
        "cost_per_acre": 35000,
        "water_requirement_mm": 600,
        "water_level": "High",
        "soil_suitability": {"loamy": 92, "clay": 68, "sandy": 78, "black": 65, "red": 80, "alluvial": 90},
        "risk_score": 0.68,
        "risk_label": "Very High",
        "msp": None,
        "demand_trend": "Volatile",
        "rotation_benefit": "Medium",
        "labour_days_per_acre": 45,
        "sustainability_score": 60,
        "glut_risk": "Very High",
    },
    "potato": {
        "name": "Potato",
        "season": "Rabi",
        "category": "Vegetable",
        "duration_days": 90,
        "yield_quintal_per_acre": 55.0,
        "price_per_quintal": 1600,
        "cost_per_acre": 32000,
        "water_requirement_mm": 500,
        "water_level": "Medium",
        "soil_suitability": {"loamy": 94, "clay": 60, "sandy": 88, "black": 62, "red": 75, "alluvial": 96},
        "risk_score": 0.52,
        "risk_label": "High",
        "msp": None,
        "demand_trend": "Medium",
        "rotation_benefit": "Medium",
        "labour_days_per_acre": 38,
        "sustainability_score": 62,
        "glut_risk": "High",
    },
    "onion": {
        "name": "Onion",
        "season": "Rabi",
        "category": "Vegetable",
        "duration_days": 120,
        "yield_quintal_per_acre": 45.0,
        "price_per_quintal": 1800,
        "cost_per_acre": 28000,
        "water_requirement_mm": 450,
        "water_level": "Medium",
        "soil_suitability": {"loamy": 88, "clay": 65, "sandy": 82, "black": 78, "red": 70, "alluvial": 85},
        "risk_score": 0.60,
        "risk_label": "High",
        "msp": None,
        "demand_trend": "Volatile",
        "rotation_benefit": "Low",
        "labour_days_per_acre": 32,
        "sustainability_score": 58,
        "glut_risk": "High",
    },
    "sugarcane": {
        "name": "Sugarcane",
        "season": "Annual",
        "category": "Cash Crop",
        "duration_days": 360,
        "yield_quintal_per_acre": 350.0,
        "price_per_quintal": 340,
        "cost_per_acre": 45000,
        "water_requirement_mm": 1800,
        "water_level": "Very High",
        "soil_suitability": {"loamy": 90, "clay": 88, "sandy": 50, "black": 82, "red": 60, "alluvial": 94},
        "risk_score": 0.40,
        "risk_label": "Medium",
        "msp": 340,
        "demand_trend": "Stable",
        "rotation_benefit": "Low",
        "labour_days_per_acre": 55,
        "sustainability_score": 40,
        "glut_risk": "Medium",
    },
    "groundnut": {
        "name": "Groundnut",
        "season": "Kharif",
        "category": "Oilseed",
        "duration_days": 120,
        "yield_quintal_per_acre": 9.5,
        "price_per_quintal": 6377,
        "cost_per_acre": 14200,
        "water_requirement_mm": 500,
        "water_level": "Medium",
        "soil_suitability": {"loamy": 78, "clay": 50, "sandy": 95, "black": 65, "red": 90, "alluvial": 70},
        "risk_score": 0.33,
        "risk_label": "Medium",
        "msp": 6377,
        "demand_trend": "High",
        "rotation_benefit": "High",
        "labour_days_per_acre": 20,
        "sustainability_score": 86,
        "glut_risk": "Low",
    },
    "moong": {
        "name": "Moong (Green Gram)",
        "season": "Zaid",
        "category": "Pulse",
        "duration_days": 70,
        "yield_quintal_per_acre": 5.5,
        "price_per_quintal": 8558,
        "cost_per_acre": 9500,
        "water_requirement_mm": 250,
        "water_level": "Low",
        "soil_suitability": {"loamy": 90, "clay": 68, "sandy": 88, "black": 75, "red": 85, "alluvial": 86},
        "risk_score": 0.29,
        "risk_label": "Low",
        "msp": 8558,
        "demand_trend": "Very High",
        "rotation_benefit": "Very High",
        "labour_days_per_acre": 12,
        "sustainability_score": 92,
        "glut_risk": "Low",
    },
    "barley": {
        "name": "Barley",
        "season": "Rabi",
        "category": "Cereal",
        "duration_days": 110,
        "yield_quintal_per_acre": 16.0,
        "price_per_quintal": 1980,
        "cost_per_acre": 11500,
        "water_requirement_mm": 350,
        "water_level": "Low",
        "soil_suitability": {"loamy": 88, "clay": 78, "sandy": 85, "black": 70, "red": 72, "alluvial": 82},
        "risk_score": 0.26,
        "risk_label": "Low",
        "msp": 1980,
        "demand_trend": "Stable",
        "rotation_benefit": "High",
        "labour_days_per_acre": 14,
        "sustainability_score": 78,
        "glut_risk": "Low",
    },
    "sunflower": {
        "name": "Sunflower",
        "season": "Zaid",
        "category": "Oilseed",
        "duration_days": 95,
        "yield_quintal_per_acre": 7.0,
        "price_per_quintal": 6400,
        "cost_per_acre": 12500,
        "water_requirement_mm": 400,
        "water_level": "Medium",
        "soil_suitability": {"loamy": 86, "clay": 72, "sandy": 80, "black": 85, "red": 82, "alluvial": 84},
        "risk_score": 0.34,
        "risk_label": "Medium",
        "msp": 6400,
        "demand_trend": "Medium",
        "rotation_benefit": "High",
        "labour_days_per_acre": 15,
        "sustainability_score": 80,
        "glut_risk": "Low",
    },
    "chilli": {
        "name": "Chilli",
        "season": "Kharif",
        "category": "Vegetable",
        "duration_days": 150,
        "yield_quintal_per_acre": 12.0,
        "price_per_quintal": 7500,
        "cost_per_acre": 30000,
        "water_requirement_mm": 600,
        "water_level": "Medium",
        "soil_suitability": {"loamy": 90, "clay": 62, "sandy": 75, "black": 80, "red": 85, "alluvial": 84},
        "risk_score": 0.58,
        "risk_label": "High",
        "msp": None,
        "demand_trend": "High",
        "rotation_benefit": "Medium",
        "labour_days_per_acre": 42,
        "sustainability_score": 65,
        "glut_risk": "Medium",
    },
}

# State-wise soil prevalence hint for realism
STATE_SOIL_MAP = {
    "punjab": "alluvial",
    "haryana": "alluvial",
    "uttar pradesh": "alluvial",
    "bihar": "alluvial",
    "west bengal": "alluvial",
    "maharashtra": "black",
    "gujarat": "black",
    "madhya pradesh": "black",
    "karnataka": "red",
    "andhra pradesh": "red",
    "telangana": "red",
    "tamil nadu": "red",
    "rajasthan": "sandy",
    "odisha": "red",
    "chhattisgarh": "red",
}

def get_crop_list() -> List[dict]:
    result = []
    for key, val in CROP_DATABASE.items():
        entry = {"id": key, **val}
        result.append(entry)
    return result

def get_crop(crop_id: str) -> dict | None:
    return CROP_DATABASE.get(crop_id.lower())

def compute_soil_suitability(crop_id: str, soil_type: str) -> int:
    crop = get_crop(crop_id)
    if not crop:
        return 50
    return crop["soil_suitability"].get(soil_type.lower(), 65)
